---
title: "S&DS 361 Jan 23"
output: html_document
date: "2024-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(pubtheme)
```

```{r}
## vix.ev.market.share.data.r

df = data.frame(year = 2015:2023,
               ev = c(0.3, 0.4, 0.5, 1.2, 1.3,
                      1.6, 2.6, 5.2, 6.9),
               hev = c(1.8, 2, 2.1, 2.5, 3.5, 
                       4, 5, 5.5, 8.3))
df$other = 100 - df$ev - df$hev
df
```
```{r}
## stacked bar chart

# making the df long from wide
dg = df %>%
  pivot_longer(cols = c(ev, hev, other)) %>%
  mutate(year = as.character(year))
dg

## two equivalent ways to do same thing
pivot_longer(df, cols = c(ev, hev, other))
dg = df %>%
  pivot_longer(cols = c(ev, hev, other))

# stacked bar chart
ggplot(dg,
       aes(x = value,
           y = year,
           fill = name)) +
  geom_col()

## copy from pubtheme and edit
title = "EV, HEV, and other vehicle Market Share" 
g = ggplot(dg, 
           aes(x = value, 
               y = year, 
               label = round(value,1),
               fill = name)) +
  geom_col(width = 0.8) + 
  labs(title    = title,
       x        = 'Market Share', ## Optional. 
       y        = 'Year')  ## Optional. Upper Lower.
g

## stacked barchart without other
title = "EV, HEV, and other vehicle Market Share" 
g = ggplot(dg %>% filter(name != 'other'), 
           aes(x = value, 
               y = year, 
               label = round(value,1),
               fill = name)) +
  geom_col(width = 0.8) + 
  labs(title    = title,
       x        = 'Market Share', ## Optional. 
       y        = 'Year')  ## Optional. Upper Lower.
g
```

