install.packages("tidyverse")
install.packages("knitr")
install.packages("plotly")
install.packages("scales")
install.packages("DT")
install.packages("leaflet")
install.packages('terra')
install.packages("gganimate")
install.packages('gifski')
install.packages('png')
install.packages("corrplot")
install.packages("GGally")
install.packages("ggmap")
install.packages("shiny")
install.packages("MASS")
install.packages("lme4")
install.packages("arm")
install.packages("pROC")
install.packages("MLmetrics")
install.packages("viridis")
install.packages("RSelenium")
install.packages("rvest")
install.packages("randomForest")
install.packages("devtools")
install.packages("splines")
install.packages("RecordLinkage")
install.packages("ff")
install.packages("rsconnect")
install.packages('grid')
install.packages('foreign')
install.packages('maps')
install.packages('timeDate')
install.packages('tidycensus')

## Install packages from my GitHub
devtools::install_github("bmacGTPM/pubtheme")

