---
title: "Jan 23"
author: "Xinran Zhang"
date: "2024-01-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(pubtheme)
```

```{r}
# viz.ev.matket.share.data.r
df = data.frame(year = 2015:2023,
                ev = c(0.3, 0.4, 0.5, 1.2, 1.3, 
                       1.6, 2.6, 5.2, 6.9),
                hev = c(1.8, 2, 2.1, 2.5, 3.5, 
                        4, 5, 5.5, 8.3))
df$other = 100 - df$ev - df$hev
df
```

```{r}
# stacked bar chart
dg = df %>%
  pivot_longer(cols = c(ev, hev, other)) %>%
  mutate(year = as.character(year))
dg

# two equivalent ways to do same thing
# pivot_longer(df, cols = c(ev, hev, other))
# df %>%
#   pivot_longer(cols = c(ev, hev, other))
```


```{r}
ggplot(dg,
       aes(x = value,
           y = year,
           fill = name)) +
  geom_col()
```


```{r}
# copy from pubtheme and edit
title = "EV, HEV, and Other Vehicle Market Share"
g = ggplot(dg,
           aes(x = value,
               y = year,
               label = round(value, 1),
               fill = name)) +
  geom_col(width = 0.8) + 
  geom_text(hjust = -0.1) + ## optional numbers with reasonable number of digits
  labs(title    = title,
       x        = 'Market Share', ## Optional. 
       y        = 'Year')  ## Optional. Upper Lower.

g %>%
  pub(type = 'bar')
```

```{r}
# Stacked bar chart without other
title = "EV, HEV, and Other  Vehicle Market Share"
g = ggplot(dg %>% filter (name != 'other'), ## dg[dg$name != 'other', ]
           aes(x = value,
               y = year,
               label = round(value, 1),
               fill = name)) +
  geom_col(width = 0.8) + 
  geom_text(hjust = -0.1) + ## optional numbers with reasonable number of digits
  labs(title    = title,
       x        = 'Market Share', ## Optional. 
       y        = 'Year')  ## Optional. Upper Lower.

g %>%
  pub(type = 'bar')
```

